// @mythicalos/ui-core — barrel. The framework-agnostic core: pure logic + types only, ZERO
// `preact`/`react` imports (enforced by test/agnostic.test.ts). Both the Preact and React bindings
// import from here so they derive identical classes/behavior from one source.

export { buttonClass, type BtnVariant, type BtnState } from "./logic/button.js";

export {
  nextPollDelay,
  makePollEpochGuard,
  runPollTick,
  shouldResetEpoch,
  POLL_JITTER_RATIO,
  POLL_BACKOFF_CAP_MS,
  type PollResult,
  type PollEpochGuard,
  type PollTickIO,
} from "./logic/poll.js";

export { typedNameMatches, BULLET_ICON, type DialogBullet } from "./logic/dialog.js";

export {
  POPOVER_CARET,
  POPOVER_CHECK,
  POPOVER_GAP_PX,
  POPOVER_BREATHING_PX,
  POPOVER_EMPTY_VALUE,
  POPOVER_DEFAULT_POSITION,
  POPOVER_CLASS,
  POPOVER_DECORATIVE_ARIA,
  POPOVER_SEPARATOR_ARIA,
  resolvePopoverPlacement,
  resolvePopoverAlign,
  resolvePopoverPosition,
  samePopoverPosition,
  popoverTriggerClass,
  popoverPanelClass,
  popoverItemClass,
  popoverIds,
  popoverTriggerAria,
  popoverPanelAria,
  popoverMenuAria,
  popoverItemAria,
  popoverTriggerKeyAction,
  popoverPanelKeyAction,
  popoverKeyHandled,
  popoverAppliesToFocus,
  edgePopoverIndex,
  stepPopoverIndex,
  initialPopoverIndex,
  resolvePopoverIndex,
  popoverTriggerText,
  popoverHasSlotContent,
  type PopoverItem,
  type PopoverPlacement,
  type PopoverAlign,
  type PopoverPosition,
  type PopoverRect,
  type PopoverSize,
  type PopoverViewport,
  type PopoverTriggerState,
  type PopoverIds,
  type PopoverTriggerAria,
  type PopoverPanelAria,
  type PopoverMenuAria,
  type PopoverItemAria,
  type PopoverTriggerKeyAction,
  type PopoverPanelKeyAction,
  type PopoverTriggerText,
  type PopoverTriggerTextOptions,
} from "./logic/popover.js";

export {
  composeToastText,
  TOAST_SEP,
  type ToastStatus,
  type ToastSpec,
  type ToastBus,
} from "./logic/toast.js";

export { gaugeTone, gaugeGeom, type GaugeGeom } from "./logic/gauge.js";

export {
  statusLineClass,
  bannerClass,
  BANNER_ICON,
  type Tone,
  type StatusTone,
  type BannerTone,
} from "./logic/tone.js";

// ── the chip family (the design system's Chip card, v2): Chip · ChipFlag · ChipDropdown ──
export {
  chipClass,
  chipCountText,
  chipRemoveLabel,
  chipFlagClass,
  chipDropdownClass,
  chipDropdownValueText,
  chipDropdownActivate,
  CHIP_TONES,
  CHIP_SIZES,
  CHIP_PARTS,
  CHIP_REMOVE_GLYPH,
  CHIP_REMOVE_LABEL,
  CHIP_FLAG_TONES,
  CHIP_FLAG_PARTS,
  CHIP_DROPDOWN_PARTS,
  CHIP_DROPDOWN_CARET,
  CHIP_DROPDOWN_EMPTY_VALUE,
  type ChipTone,
  type ChipSize,
  type ChipState,
  type ChipFlagTone,
  type ChipDropdownState,
  type ChipDropdownActivation,
} from "./logic/chip.js";

// ── theme toggle (ds/components-theme-toggle): segmented · icon · switch ──
export {
  THEME_MODES,
  THEME_TOGGLE_PARTS,
  THEME_ICON_PARTS,
  THEME_SWITCH_PARTS,
  THEME_MODE_LABELS,
  THEME_MODE_ICONS,
  THEME_TOGGLE_GROUP_LABEL,
  THEME_ICON_LABEL,
  THEME_SWITCH_LABEL,
  THEME_ICONS,
  THEME_ICON_STROKE,
  isThemeMode,
  themeModeIndex,
  resolveThemeIsDark,
  themeGlyph,
  themeIconTarget,
  themeToggleKeyAction,
  nextThemeMode,
  themeToggleTabStop,
  themeLabel,
  themeSwitchHasReadableText,
  themeToggleClass,
  themeIconClass,
  type ThemeMode,
  type ResolvedTheme,
  type ThemeIconName,
  type ThemeIconShape,
  type ThemeIconSpec,
  type ThemeToggleState,
  type ThemeIconState,
  type ThemeToggleKeyAction,
} from "./logic/theme-toggle.js";

// ── small atoms graduated out of a single product: save-bar, stat-tiles, git-chip ──
export {
  saveBarNote,
  saveBarDirty,
  saveBarClass,
  SAVE_BAR_PARTS,
  SAVE_BAR_SEP,
  SAVE_BAR_DISCARD_LABEL,
  SAVE_BAR_SAVE_LABEL,
  type SaveBarNote,
} from "./logic/save-bar.js";

export {
  statTilesClass,
  statTileClass,
  STAT_TILE_PARTS,
  formatStatCompact,
  formatStatCount,
  formatStatUsd,
  formatStatPercent,
  STAT_TILE_EMPTY,
  STAT_TILE_MINUS,
  type StatTile,
  type StatTileTone,
} from "./logic/stat-tiles.js";

export {
  gitFlags,
  hasGitStatus,
  gitBranchLabel,
  gitChipClass,
  gitFlagClass,
  gitChipNote,
  GIT_CHIP_PARTS,
  GIT_BRANCH_GLYPH,
  GIT_BRANCH_UNKNOWN,
  GIT_DETACHED_LABEL,
  GIT_CLEAN_LABEL,
  GIT_LOADING_NOTE,
  GIT_UNAVAILABLE_NOTE,
  GIT_STALE_LABEL,
  GIT_STALE_TITLE,
  type GitStatus,
  type GitFlag,
  type GitFlagTone,
  type GitChipState,
} from "./logic/git-chip.js";

// ── file explorer & markdown preview (ds/components-file-explorer) ──
export {
  // tree derivation
  deriveFileTreeRows,
  countFileRows,
  countLoadedFiles,
  classifyDirNode,
  repoBadges,
  isUsableEntryName,
  isUsableRootKey,
  MAX_TREE_DEPTH,
  // glyphs
  NODE_GLYPH,
  CHEVRON_OPEN,
  CHEVRON_CLOSED,
  chevronGlyph,
  scopeGlyph,
  SCOPE_CARET,
  fileGlyph,
  isMarkdownName,
  // path + breadcrumb composition
  NODE_ID_SEP,
  nodeId,
  splitNodeId,
  childRelPath,
  parentRelPath,
  ancestorRelPaths,
  BREADCRUMB_SEP,
  breadcrumbSegments,
  buildBreadcrumb,
  // git marks
  gitMarkTone,
  gitMarkLabel,
  gitMarkClass,
  previewBadge,
  previewBadgeClass,
  // honest states
  HONEST_STATUSES,
  isHonestStatus,
  honestNoteText,
  honestNoteClass,
  treeNoteClass,
  treeNoteRowClass,
  previewNoteText,
  previewNoteClass,
  previewBodyMode,
  previewMeta,
  // formatting
  formatFileSize,
  formatRelativeTime,
  SECONDS_THRESHOLD,
  // class strings
  MAX_INDENT_DEPTH,
  indentClass,
  dirRowClass,
  fileRowClass,
  badgeClass,
  scopeItemClass,
  type FileTreeMode,
  type FileNodeKind,
  type GitMark,
  type GitMarkTone,
  type FileTreeRootSpec,
  type FileTreeEntry,
  type DirState,
  type HonestStatus,
  type HonestSurface,
  type FilePreviewState,
  type FileRowBadge,
  type PreviewBadgeState,
  type PreviewBadge,
  type FileTreeDirRow,
  type FileTreeFileRow,
  type FileTreeNoteRow,
  type FileTreeRow,
  type DeriveFileTreeInput,
  type FileScopeOption,
} from "./logic/file-explorer.js";

// ── session-card (design registry `session-card` v1) ──
export {
  ctxBand,
  ctxReading,
  ctxFillPct,
  ctxValueText,
  ctxNoteText,
  ctxMeterClass,
  ctxBarGeom,
  normalizeCtxThresholds,
  sessionStatus,
  sessionStatusClass,
  sessionStatusText,
  sessionCardIsStale,
  sessionCardStale,
  sessionCardClass,
  sessionAvatarInitial,
  sessionSubline,
  sessionSpineNodes,
  sessionSpineLabel,
  sessionSpineSavedText,
  sessionSpineSummary,
  spineNodeClass,
  CTX_THRESHOLDS_DEFAULT,
  CTX_UNKNOWN_TEXT,
  CTX_LABEL,
  CTX_BAR_SPAN,
  CTX_BAR_HEIGHT,
  CTX_BAR_VIEWBOX,
  CTX_BAR_TICK_WIDTH,
  SESSION_CARD_SEP,
  SESSION_STATUS_UNKNOWN,
  SESSION_AVATAR_UNKNOWN,
  SPINE_SAVED_UNKNOWN,
  SPINE_MAX_NODES,
  type CtxThresholds,
  type CtxBand,
  type CtxBarTick,
  type CtxBarGeom,
  type SessionLifecycle,
  type SessionActivity,
  type SessionStatusTone,
  type SessionStatusKey,
  type SessionStatus,
  type SessionStatusInput,
  type SessionSpine,
  type SpineNode,
  type SpineSummary,
} from "./logic/session-card.js";

// ── terminal set (ds/components-terminal v2): terminal · queue-row · send-bar ──
export {
  DEFAULT_DELIVERY_CLASS,
  DELIVERY_CLASSES,
  DELIVERY_HINT,
  SEND_PLACEHOLDER,
  SEND_DISABLED_FALLBACK,
  SEND_BUTTON_LABEL,
  SENDBAR_CLASSES,
  canSend,
  clearDraftOnSend,
  deliveryClassButtonClass,
  deliveryClassLabel,
  keyAction,
  makeSendGate,
  resolveSend,
  sendBarClass,
  sendPlaceholder,
  showDeliveryHint,
  type DeliveryClass,
  type KeyAction,
  type SendGate,
} from "./logic/sendbar.js";

export {
  QUEUE_CANCEL_ASK,
  QUEUE_CANCEL_LABEL,
  QUEUE_CANCEL_NO,
  QUEUE_CANCEL_YES,
  QUEUE_EMPTY_COPY,
  QUEUE_LOADING_COPY,
  QUEUE_STALE_COPY,
  QUEUE_UNAVAILABLE_COPY,
  QUEUE_CLASSES,
  canCancelRow,
  cancelReducer,
  isFreshSource,
  queueBadgeClass,
  queueBadgeLabel,
  queueRowClass,
  queueStatusLabel,
  queueView,
  shouldDisarmCancel,
  unavailableText,
  type CancelEvent,
  type CancelState,
  type QueueItem,
  type QueueItemStatus,
  type QueueSource,
  type QueueUnavailableReason,
  type QueueView,
} from "./logic/queue.js";

export {
  ROW_SCOPE,
  TERM_CLASS,
  TERM_CLASSES,
  TERM_FAILED_COPY,
  TERM_LOADING_COPY,
  TERM_MISSING_COPY,
  TERM_NO_EVENTS_COPY,
  TERM_ROW_KINDS,
  TERM_STALE_COPY,
  TERM_STOP_KEY_HINT,
  TERM_STOP_LABEL,
  TERM_UNADDRESSABLE_COPY,
  TERM_WAKE_UNAVAILABLE_COPY,
  TURN_IDLE_COPY,
  TURN_IN_FLIGHT_COPY,
  ROW_COLLAPSE_LABEL,
  ROW_EXPAND_LABEL,
  currentWakeRows,
  expandLabel,
  historySegmentCaption,
  historyToggleLabel,
  isExpandable,
  lastBoundaryIndex,
  noiseShow,
  rowKey,
  rowKeys,
  scopedRowKeys,
  segmentKeys,
  shouldStopOnKey,
  sourceRows,
  stopButtonClass,
  termRowClass,
  termTitleText,
  transcriptView,
  turnCaption,
  uniqueKeys,
  visibleRows,
  type TermRow,
  type TermRowKind,
  type TermSource,
  type TermView,
  type TranscriptSegment,
} from "./logic/terminal.js";
